# name: Test github actions

# on: push

# jobs:
#   run-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout the repo
#         uses: actions/checkout@v2

#       - name: Check for dockerenv file
#         run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
#       - name: Open the backend and Install dependencies
#         run: npm i

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Get commit hash
#         id: get-commit-hash
#         run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
#       - name: Get timestamp
#         id: get-timestamp
#         run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M')"


#       - name: Build, tag, and push the image to Amazon ECR
#         id: build-image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
#           IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


        
#       # - name: Build the image
#       #   run: cd container & docker build -t my-node-app .


name: Test GitHub Actions

on:
  push:
    branches:
        - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Check for dockerenv file
        run: |
          if [ -f /.dockerenv ]; then
            echo "Found dockerenv"
          else
            echo "No dockerenv"
          fi

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: tsc --project tsconfig.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build, tag, and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
          IMAGE_TAG: ${{ env.commit_hash }}-${{ env.timestamp }}
        run: |
          docker build -t my-ecr-repo .
          docker tag my-ecr-repo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:latest
      - name: Update cluster
        run: |
          ecs_service_name=${{ECS_SERVICE_NAME}}
          ecs_cluster_name=${{ECS_CLUSTER_NAME}}

          # Get the latest task definition
          task_definition_arn=$(aws ecs describe-services \
            --cluster $ecs_cluster_name \
            --services $ecs_service_name \
            --query 'services[0].taskDefinition' \
            --output text)

          # Register a new task definition with the updated image
          new_task_definition=$(aws ecs describe-task-definition \
            --task-definition $task_definition_arn \
            --query 'taskDefinition')

          # Replace the image with the latest one
          new_task_definition=$(echo $new_task_definition | jq --arg IMAGE "<your-account-id>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-ecr-repository:latest" '.containerDefinitions[0].image = $IMAGE')

          # Remove unnecessary keys
          new_task_definition=$(echo $new_task_definition | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          # Register the new task definition
          registered_task_definition=$(echo $new_task_definition | aws ecs register-task-definition --cli-input-json /dev/stdin)

          # Update ECS service to use the new task definition
          new_task_definition_arn=$(echo $registered_task_definition | jq -r '.taskDefinition.taskDefinitionArn')

          aws ecs update-service --cluster $ecs_cluster_name --service $ecs_service_name --task-definition $new_task_definition_arn
